import './polyfills.js';
import * as pdfjs from 'pdfjs-dist/legacy/build/pdf.mjs';
import { PDFDocument } from 'pdf-lib';
import { Document, Paragraph, TextRun, ImageRun, Packer } from 'docx';
import { zipSync, strToU8 } from 'fflate';
import * as XLSX from 'xlsx';
import mammoth from 'mammoth/mammoth.browser';
import DOMPurify from 'dompurify';
import { readCaj } from './caj.js';
import workerUrl from 'pdfjs-dist/legacy/build/pdf.worker.min.mjs?url';

pdfjs.GlobalWorkerOptions.workerSrc=workerUrl;
const assetUrl=name=>new URL('../'+name,import.meta.url).href;
const MIME={docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',pdf:'application/pdf',txt:'text/plain;charset=utf-8',html:'text/html;charset=utf-8',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',csv:'text/csv;charset=utf-8',json:'application/json',jpg:'image/jpeg',png:'image/png',webp:'image/webp',zip:'application/zip'};
const MAX_RESULT=64*1024*1024;
const sleepFrame=()=>new Promise(r=>setTimeout(r,0));
const result=(name,target,data,warning)=>({name:name.replace(/\.[^.]+$/,'')+'.'+target,blob:new Blob([data],{type:MIME[target]}),warning});
const cleanText=s=>String(s).replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'');
async function recognize(image,progress){
  progress(5,'正在准备中英文识别，首次使用需要下载模型…');
  const {createWorker}=await import('tesseract.js');
  let worker;
  try{worker=await createWorker('chi_sim+eng',1,{workerPath:assetUrl('ocr/worker.min.js'),corePath:assetUrl('ocr'),langPath:assetUrl('ocr/lang'),gzip:!window.AndroidConverter,workerBlobURL:false,logger:m=>{if(m.status==='recognizing text')progress(20+(m.progress||0)*70,'正在识别文字…');}});const {data}=await worker.recognize(image);return cleanText(data.text);}catch(e){console.error('OCR failed',e);throw new Error('文字识别未完成，请确认网络正常，或改用保留页面外观模式。');}finally{if(worker)await worker.terminate();}
}
async function docxFromPages(pages,{images=false}={}){
  const sections=pages.map(p=>{const children=[];if(images&&p.image){const ratio=Math.min(620/(p.width||500),850/(p.height||700));children.push(new Paragraph({spacing:{after:0},children:[new ImageRun({data:p.image,type:'png',transformation:{width:(p.width||500)*ratio,height:(p.height||700)*ratio}})]}));}else{for(const line of cleanText(p.text||'').split('\n'))children.push(new Paragraph({children:[new TextRun({text:line,font:'Arial',size:22})],spacing:{after:100,line:300}}));if(!children.length)children.push(new Paragraph(''));}return{properties:{page:{size:{width:11906,height:16838},margin:{top:1000,right:1000,bottom:1000,left:1000}}},children};});
  const blob=await Packer.toBlob(new Document({creator:'转一下',title:'转换文档',sections}));if(blob.size>MAX_RESULT)throw new Error('转换结果过大，请减少页面后再试。');return blob;
}
function extractLines(items){const rows=[];for(const t of items){if(!('str'in t)||!t.str)continue;const y=t.transform[5];let row=rows.find(r=>Math.abs(r.y-y)<Math.max(2,Math.abs(t.transform[3])*.18));if(!row){row={y,items:[]};rows.push(row);}row.items.push(t);}return rows.sort((a,b)=>b.y-a.y).map(r=>{let s='',end=null;for(const t of r.items.sort((a,b)=>a.transform[4]-b.transform[4])){if(end!==null&&t.transform[4]-end>Math.max(2,Math.abs(t.transform[3])*.3))s+=' ';s+=t.str;end=t.transform[4]+t.width;}return s;}).join('\n');}
async function canvasBytes(canvas,type='png'){return new Uint8Array(await (await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('图片无法导出。')),MIME[type],.9))).arrayBuffer());}
async function renderPage(page,width=1500){const v=page.getViewport({scale:1});const viewport=page.getViewport({scale:Math.min(width/v.width,2.5)});const canvas=document.createElement('canvas');canvas.width=Math.round(viewport.width);canvas.height=Math.round(viewport.height);await page.render({canvas,canvasContext:canvas.getContext('2d'),viewport,background:'white'}).promise;return canvas;}
async function openPdf(data){try{const pdf=await pdfjs.getDocument({data,cMapUrl:assetUrl('pdf/cmaps/'),cMapPacked:true,standardFontDataUrl:assetUrl('pdf/standard_fonts/'),wasmUrl:assetUrl('pdf/wasm/'),enableScripting:false,isEvalSupported:false}).promise;if(pdf.numPages>80){await pdf.loadingTask.destroy();throw new Error('当前手机版支持最多80页，请先拆分文档。');}return pdf;}catch(e){console.error('PDF load failed',e);if(e.name==='PasswordException')throw new Error('PDF 已加密，请先移除密码后再转换。');throw new Error(e.message?.includes('80页')?e.message:'文件无法作为 PDF 读取，请确认文件完整。');}}
async function convertPdf(data,fileName,options,progress){
  if(options.target==='pdf'){const doc=await PDFDocument.load(data);if(doc.getPageCount()>80)throw new Error('当前手机版支持最多80页。');return[result(fileName,'pdf',await doc.save())];}
  const pdf=await openPdf(data),pages=[],output={};let total=0,recognized=0,visualFallback=0;
  try{for(let i=1;i<=pdf.numPages;i++){progress((i-1)/pdf.numPages*90,`正在处理第 ${i} / ${pdf.numPages} 页…`);const page=await pdf.getPage(i);if(['jpg','png'].includes(options.target)){const c=await renderPage(page);const bytes=await canvasBytes(c,options.target);total+=bytes.length;if(total>MAX_RESULT)throw new Error('图片结果过大，请减少页面或改为 JPG。');output[`第${String(i).padStart(3,'0')}页.${options.target}`]=bytes;c.width=c.height=1;continue;}
      const items=await page.getTextContent();let text=extractLines(items.items),image=null;const v=page.getViewport({scale:1});
      if(options.layout==='visual'&&options.target==='docx'){const c=await renderPage(page,1200);image=await canvasBytes(c);c.width=c.height=1;}
      else if(text.replace(/\s/g,'').length<3&&options.ocr){const c=await renderPage(page,1700);text=await recognize(c,(p,m)=>progress(((i-1)+p/100)/pdf.numPages*90,`第 ${i} 页 · ${m}`));recognized++;c.width=c.height=1;}
      else if(!text.trim()&&options.target==='docx'){const c=await renderPage(page,1200);image=await canvasBytes(c);visualFallback++;c.width=c.height=1;}
      if(image){total+=image.length;if(total>MAX_RESULT)throw new Error('Word 结果过大，请减少页面。');}
      pages.push({text,image,width:v.width,height:v.height});await sleepFrame();
    }
    progress(95,'正在生成文件…');if(['jpg','png'].includes(options.target))return[result(fileName,'zip',zipSync(output,{level:0}))];if(options.target==='txt'){if(!pages.some(p=>p.text.trim()))throw new Error('未读取到文字，请开启扫描件识别。');return[result(fileName,'txt',pages.map(p=>p.text).join('\n\n'))];}
    const bytes=await docxFromPages(pages,{images:options.layout==='visual'||visualFallback>0});const warning=options.layout==='visual'?'原页面已放入 Word，图片里的文字不可直接编辑。':visualFallback?`${visualFallback} 页没有文字层，已保存为页面图片。其余页为文字提取。`:recognized?`${recognized} 页已识别文字，请核对数字、公式和表格。`:'已提取可编辑文字，不保留原图表；如需完整外观可选图片模式。';return[result(fileName,'docx',bytes,warning)];
  }finally{await pdf.loadingTask.destroy();}
}
async function imageCanvas(file,maxWidth=2200){const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();if(maxWidth===Infinity&&image.naturalWidth*image.naturalHeight>16000000)throw new Error('图片超过1600万像素，请先缩小后再转换。');const scale=maxWidth===Infinity?1:Math.min(1,maxWidth/image.naturalWidth,3500/image.naturalHeight);const c=document.createElement('canvas');c.width=Math.max(1,Math.round(image.naturalWidth*scale));c.height=Math.max(1,Math.round(image.naturalHeight*scale));const ctx=c.getContext('2d');ctx.drawImage(image,0,0,c.width,c.height);return c;}catch(e){throw new Error(e.message?.includes('1600万')?e.message:'这张图片无法读取，请使用 JPG、PNG 或 WebP。');}finally{URL.revokeObjectURL(url);}}
async function imagesPdf(files,progress){const pdf=await PDFDocument.create();for(let i=0;i<files.length;i++){progress(i/files.length*90,`正在合成第 ${i+1} / ${files.length} 张图片…`);const canvas=await imageCanvas(files[i]),image=await pdf.embedPng(await canvasBytes(canvas)),page=pdf.addPage([595.28,841.89]);const scale=Math.min(555/image.width,802/image.height);const w=image.width*scale,h=image.height*scale;page.drawImage(image,{x:(595.28-w)/2,y:(841.89-h)/2,width:w,height:h});canvas.width=canvas.height=1;}return[result(files.length>1?'合并图片.pdf':files[0].name,'pdf',await pdf.save())];}
async function textPdf(pages,progress){const pdf=await PDFDocument.create(),width=1240,height=1754,margin=90,lineHeight=38;let canv=null,ctx=null,y=0,rendered=0;const start=()=>{canv=document.createElement('canvas');canv.width=width;canv.height=height;ctx=canv.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,width,height);ctx.fillStyle='#182238';ctx.font='26px sans-serif';y=margin;};const flush=async()=>{const image=await pdf.embedPng(await canvasBytes(canv));const page=pdf.addPage([595.28,841.89]);page.drawImage(image,{x:0,y:0,width:595.28,height:841.89});rendered++;if(rendered>80)throw new Error('生成的 PDF 超过80页，请减少文字。');canv.width=canv.height=1;};start();for(let p=0;p<pages.length;p++){progress(p/pages.length*85,'正在生成 PDF 页面…');for(const line of cleanText(pages[p].text).split('\n')){let current='';for(const char of line){if(ctx.measureText(current+char).width>width-margin*2){ctx.fillText(current,margin,y);y+=lineHeight;current='';if(y>height-margin){await flush();start();}}current+=char;}ctx.fillText(current,margin,y);y+=lineHeight;if(y>height-margin){await flush();start();}}if(p<pages.length-1){await flush();start();}}await flush();return pdf.save();}
export function convertSheet(data,name,target){let wb;const lower=name.toLowerCase();if(lower.endsWith('.json')){let value;try{value=JSON.parse(new TextDecoder().decode(data));}catch{throw new Error('JSON 内容无法解析。');}if(!Array.isArray(value)||value.some(v=>!v||typeof v!=='object'||Array.isArray(v)))throw new Error('JSON 需要是对象数组，例如 [{"姓名":"小明","成绩":90}]。');if(value.length>50000)throw new Error('当前手机版支持最多50000行。');wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(value),'Sheet1');}else wb=XLSX.read(data,{type:'array',cellDates:true,dense:true});const sheet=wb.Sheets[wb.SheetNames[0]];if(!sheet)throw new Error('表格中没有工作表。');if(sheet['!ref']){const r=XLSX.utils.decode_range(sheet['!ref']);if(r.e.r>50000||r.e.c>500)throw new Error('表格过大，手机版支持最多50000行、500列。');}let out;if(target==='xlsx')out=XLSX.write(wb,{type:'array',bookType:'xlsx'});else if(target==='csv')out='\ufeff'+XLSX.utils.sheet_to_csv(sheet);else out=JSON.stringify(XLSX.utils.sheet_to_json(sheet,{defval:null}),null,2);return result(name,target,out,wb.SheetNames.length>1&&target!=='xlsx'?'已导出第一张工作表。':undefined);}
export async function convertFile(files,options,progress=()=>{}){
  const file=files[0],name=file.name.replace(/[\\/\u0000-\u001f]/g,'_');progress(0,'正在读取文件…');if(options.tool==='image-pdf')return imagesPdf(files,progress);
  if(options.tool==='image-format'){const canvas=await imageCanvas(file,Infinity);if(options.target==='jpg'){const ctx=canvas.getContext('2d');ctx.globalCompositeOperation='destination-over';ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);}const bytes=await canvasBytes(canvas,options.target);if(options.target==='webp'&&!(bytes[0]===82&&bytes[8]===87))throw new Error('这个浏览器不支持 WebP 导出，请改选 PNG 或 JPG。');canvas.width=canvas.height=1;return[result(name,options.target,bytes)];}
  if(options.tool==='image-word'){const canvas=await imageCanvas(file,2200);const text=await recognize(canvas,progress);canvas.width=canvas.height=1;if(!text.trim())throw new Error('没有识别到文字，请选用清晰、正向的文档图片。');return[result(name,options.target,options.target==='txt'?text:await docxFromPages([{text}]),'已识别文字，请核对数字、公式和表格。')];}
  const buffer=await file.arrayBuffer();
  if(options.tool==='word-pdf'){const {wordPdf}=await import('./word-pdf.js');return[result(name,'pdf',await wordPdf(buffer,progress),'已保留基本段落、表格和图片并重排为 A4。复杂页眉页脚、分栏和公式可能改变；PDF 页面为图片。')];}
  if(options.tool==='caj-word'){const caj=readCaj(buffer);if(caj.kind==='pdf')return convertPdf(caj.data,name,options,progress);if(options.target==='docx'&&options.layout==='visual')throw new Error('这个 HN/C8 文件仅支持文字层提取，请选择“可编辑文字”。');let out;if(options.target==='docx')out=await docxFromPages(caj.pages);else if(options.target==='txt')out=caj.pages.map(p=>p.text).join('\n\n');else out=await textPdf(caj.pages,progress);return[result(name,options.target,out,caj.warning+(options.target==='pdf'?' PDF 为文字重排版。':''))];}
  if(options.tool==='pdf-word'||options.tool==='pdf-export')return convertPdf(new Uint8Array(buffer),name,options,progress);
  if(options.tool==='word-export'){if(options.target==='txt'){const value=await mammoth.extractRawText({arrayBuffer:buffer});return[result(name,'txt',value.value)];}const html=await mammoth.convertToHtml({arrayBuffer:buffer});const safe=DOMPurify.sanitize(html.value,{FORBID_TAGS:['script','style','iframe','object','embed','form'],FORBID_ATTR:['srcset']});return[result(name,'html',`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>转换文档</title><style>body{max-width:850px;margin:32px auto;padding:24px;font:16px/1.8 system-ui}img{max-width:100%}table{border-collapse:collapse}td{border:1px solid #ccc;padding:8px}</style><body>${safe}</body></html>`,'导出的 HTML 保留内容结构，复杂 Word 版式可能改变。')];}
  if(options.tool==='text-word'){let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(buffer);}catch{text=new TextDecoder('gb18030').decode(buffer);}return[result(name,options.target,options.target==='docx'?await docxFromPages([{text}]):await textPdf([{text}],progress),options.target==='pdf'?'文字已按页面重排，PDF 页面为图片。':undefined)];}
  if(options.tool==='sheet-format')return[convertSheet(new Uint8Array(buffer),name,options.target)];throw new Error('这个转换方式暂不支持。');
}
